name = "daton-api"
main = "src/index.ts"
compatibility_date = "2026-03-07"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "98e9bdb789984e62a58043f10f3fd3d2"

[observability.logs]
enabled = true
